# Generated by Django 3.1.1 on 2020-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
