# Generated by Django 3.1.1 on 2020-09-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
