# Generated by Django 3.1.1 on 2020-09-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200906_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='age_limit',
        ),
        migrations.AddField(
            model_name='genre',
            name='agelimit',
            field=models.IntegerField(choices=[(1, 'Adult'), (2, 'Young'), (3, 'Children')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genre'),
        ),
    ]
