# Generated by Django 3.1.1 on 2020-09-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200906_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='agelimit',
        ),
    ]
