# Generated by Django 3.1.1 on 2020-09-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_genre_agelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, choices=[(7, 'Children'), (12, 'Young'), (18, 'Adult')], null=True),
        ),
    ]
