# Generated by Django 3.1.1 on 2020-09-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_genre_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, choices=[(7, 'Children'), (12, 'Young'), (18, 'Adult'), (50, 'Retired')], null=True),
        ),
    ]
