# Generated by Django 3.1.1 on 2020-09-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200906_1021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'released', 'director')},
        ),
    ]
