# Generated by Django 3.1.1 on 2020-09-27 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shoes',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(50)]),
        ),
    ]
