# Generated by Django 3.1.1 on 2020-09-27 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200927_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shoes',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
