# Generated by Django 3.1.1 on 2020-09-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200927_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shoes',
            field=models.CharField(max_length=2),
        ),
    ]
